"""initial tables

Revision ID: 1f7436884053
Revises: 
Create Date: 2026-04-14 09:30:18.552724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f7436884053'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomalies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('anomaly_status', sa.String(), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('main_source', sa.String(), nullable=True),
    sa.Column('contributors', sa.String(), nullable=True),
    sa.Column('wms_score', sa.Float(), nullable=True),
    sa.Column('inverter_score', sa.Float(), nullable=True),
    sa.Column('dgr_score', sa.Float(), nullable=True),
    sa.Column('ht_score', sa.Float(), nullable=True),
    sa.Column('lt_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomalies_id'), 'anomalies', ['id'], unique=False)
    op.create_table('faults',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inverter', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('root_level', sa.String(), nullable=True),
    sa.Column('fault_type', sa.String(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('likely_causes', sa.String(), nullable=True),
    sa.Column('recommended_action', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faults_id'), 'faults', ['id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('component', sa.String(), nullable=True),
    sa.Column('prediction', sa.Float(), nullable=True),
    sa.Column('health_status', sa.String(), nullable=True),
    sa.Column('likely_cause', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_component'), 'predictions', ['component'], unique=False)
    op.create_index(op.f('ix_predictions_id'), 'predictions', ['id'], unique=False)
    op.create_index(op.f('ix_predictions_timestamp'), 'predictions', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_predictions_timestamp'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_component'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_faults_id'), table_name='faults')
    op.drop_table('faults')
    op.drop_index(op.f('ix_anomalies_id'), table_name='anomalies')
    op.drop_table('anomalies')
    # ### end Alembic commands ###
